[proyecto]
nombre      = lab1
modulo_top  = top

[dispositivo]
; Basys 3 (Artix-7 xc7a35t)
parte       = xc7a35tcpg236-1

[vivado]
; Ruta al ejecutable de Vivado.
; Si está vacío, el script lo busca automáticamente en:
;   1. Variable de entorno XILINX_VIVADO
;   2. PATH del sistema
;   3. C:/Xilinx/Vivado/<versión>/bin/
ejecutable  =
